<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>ExtractProductionItems.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="xunit.v3.mtp-off" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ExtractProductionItems\ExtractProductionItems.csproj" />
  </ItemGroup>

</Project>
